### ISSUE TITLE
loss.backward() error

### ISSUE THREAD

**Issue by acdemontic** [dogyoonlee/DP-NeRF#2]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024]], which is output 0 of LinalgVectorNormBackward0, is at version 1; expected version 0 instead.

**Comment by acdemontic** [comment]
done!
"rigid_warping.py" line 32.
modify "theta += 1.0e-10" to "theta = theta + 1.0e-10"

**Comment by tingxueronghua** [comment]
I think this problem should be noticed by the author T-T

**Comment by dogyoonlee** [comment]
@acdemontic @tingxueronghua 

Thank you for your interest on our work!
I tried our code on several environments with different version of some libraries.
I found that sometimes the error occurs and sometimes not.
The problem seems to be dependencies between libraries.
I will fix that part of the code.

Thank you for your kind suggestion!
