### ISSUE TITLE
Would you like to share the pretrained weights please?

### ISSUE THREAD

**Issue by benhenryL** [dogyoonlee/DP-NeRF#3]
Hi teams, thanks for sharing your awesome work!

I want to train your model on real scenes data, but unfortunately, I cannot because of my GPU memory limit.

Though I can reduce batch size but I want to see the result from the model that is used in your paper, so would you like to share the what you trained if it is fine?

Thanks!

**Comment by dogyoonlee** [comment]
@benhenryL 
Hello, I have a pretrained weights for all scenes that I used in the paper.
It's not difficult at all to prove the pretrained model you requested, but it would not be loaded on public code.
Because I did code refactoring to release the public code for DP-NeRF after submitting the camera-ready paper including changing the config and names of the model and variables to make the reader understand the code better.

I recommend to train the model again using another large GPU.

If it is possible, I will additionally upload the pretrained weights for some scenes.

Thank you for your attention!

**Comment by benhenryL** [comment]
Oh I see. Thanks for quick reply!

I fully understand your situation.  I tried, but I fail to get large GPU, so it would be really great for me if I can get the pretrained weights.

If you can share them via some not-public ways (ex. email), then I'm willing to let you know my email address. Or any other ways are also welcome. 

Thanks!

**Comment by dogyoonlee** [comment]
@benhenryL 

It is also possible to not use the AWP and only use the RBK to train the DP-NeRF.
If your memory is not enough to train the full model, it could be another solution to test the effectiveness of our model with only RBK.
In addition, reducing the `chunk`, `netchunk`, or `rbk_num_motion` can be helpful.

**Comment by dogyoonlee** [comment]
@benhenryL 

We add pretrained weight for blurpool scene.

If you have any additional question, feel free to ask.

Best,

**Comment by benhenryL** [comment]
I found the weight. 

Thank you for providing it!
